language: java

jdk:
    - oraclejdk7
    - openjdk7

before_script:
    - chmod +x grailsw
    - ./grailsw clean
    - ./grailsw refresh-dependencies
    - ./grailsw compile

script: ./grailsw test-app
